permissions:
  contents: write

name: Build Windows EXE
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build installer
        run: .\gradlew --no-daemon clean jpackage

      # 실패해도 여기서 exe는 받을 수 있게 아티팩트 업로드(선택아님, 강추)
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: SalesLedger-windows
          path: build/jpackage/*.exe

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/jpackage/*.exe  
          generate_release_notes: true
