permissions:
  contents: write

name: Build Windows EXE
on:
  push:
    tags: ['v*'] 
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build installer
        run: .\gradlew --no-daemon clean jpackage
      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          files: build/jpackage/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
